application: problem-generator
api_version: 1
runtime: python27
threadsafe: true


handlers:
- url: /static
  static_dir: static
  expiration: "2d"
  
- url: /questions
  script: main.logged_in_app
  secure: always
  login: required

- url: /.*
  script: main.mainapp
  secure: optional
  

libraries:
- name : webapp2
  version : "2.5.2"
- name : jinja2
  version : "latest"

  
  

